type: "orchestration"
version: "1.0"
pipeline:
  components:
    Start 0:
      type: "start"
      transitions:
        unconditional:
        - "Create Table Credit Card"
      skipped: false
      parameters:
        componentName: "Start 0"
    S3 Load Data:
      type: "s3-load"
      skipped: false
      parameters:
        componentName: "S3 Load Data"
        stage: "[Custom]"
        authentication: "Credentials"
        s3ObjectPrefix: "s3://matillionclass/Data_Masking/"
        pattern: ".csv"
        encryption: "None"
        warehouse: "DEMO_WAREHOUSE"
        database: "DEMO_DATABASE"
        schema: "DEMO_SCHEMA"
        targetTable: "CREDIT_CARD_CUSTOMERS"
        loadColumns:
        - "CUST_ID"
        - "CREDIT_CARD_NUMBER"
        - "BALANCE"
        - "PURCHASES"
        - "INSTALLMENTS_PURCHASES"
        - "CASH_ADVANCE"
        - "CREDIT_LIMIT"
        - "PAYMENTS"
        - "MINIMUM_PAYMENTS"
        - "TENURE"
        - "DATE_OF_TXN"
        format: "CSV_FILE_FORMAT"
        onError: "Abort Statement"
        sizeLimitB: ""
        purgeFiles: "False"
        truncateColumns: "False"
        forceLoad: "False"
    Create Table Credit Card:
      type: "create-table-v2"
      transitions:
        unconditional:
        - "Create File Format CSV"
      skipped: false
      parameters:
        componentName: "Create Table Credit Card"
        createMethod: "Create if not exists"
        database: "[Environment Default]"
        schema: "[Environment Default]"
        table: "CREDIT_CARD_CUSTOMERS"
        snowflakeTableType: "Permanent"
        columns:
        - - "CUST_ID"
          - "VARCHAR"
          - "20"
          - ""
          - ""
          - "Yes"
          - "Yes"
          - ""
          - ""
        - - "CREDIT_CARD_NUMBER"
          - "VARCHAR"
          - "19"
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "BALANCE"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "PURCHASES"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "INSTALLMENTS_PURCHASES"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "CASH_ADVANCE"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "CREDIT_LIMIT"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "PAYMENTS"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "MINIMUM_PAYMENTS"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "TENURE"
          - "NUMBER"
          - "10"
          - "2"
          - ""
          - "No"
          - "No"
          - ""
          - ""
        - - "DATE_OF_TXN"
          - "DATE"
          - ""
          - ""
          - ""
          - "No"
          - "No"
          - ""
          - ""
        defaultDdlCollation: ""
        primaryKeys:
        - "CUST_ID"
        clusteringKeys:
        dataRetentionTimeInDays: ""
        comment: "Table for Holding Credit Card Txns"
    SQL Script MASKING POLICIES:
      type: "sql-script"
      transitions:
        unconditional:
        - "Alter Masking Policy CREDIT_CARD"
      skipped: false
      parameters:
        componentName: "SQL Script MASKING POLICIES"
        sqlScript: "CREATE MASKING POLICY IF NOT EXISTS MASK_CREDIT_CARDS AS (CREDIT_CARD_NUMBER\
          \ STRING) \nRETURNS STRING -> \nCASE \n   WHEN CURRENT_ROLE() IN ('DEVELOPER','ACCOUNTADMIN')\
          \ THEN CREDIT_CARD_NUMBER\n   WHEN CURRENT_ROLE() IN ('ANALYST') THEN REGEXP_REPLACE(CREDIT_CARD_NUMBER,\
          \ '^.{7}', '*******')\n   WHEN CURRENT_ROLE() IN ('TESTER') THEN '**********'\n\
          \   ELSE '***CAN NOT BE SEEN***'\nEND"
    Alter Masking Policy CREDIT_CARD:
      type: "unknown-orchestration"
      transitions:
        unconditional:
        - "S3 Load Data"
      skipped: false
      parameters:
        "1": "Alter Masking Policy CREDIT_CARD"
        "2": "DEMO_DATABASE"
        "3": "DEMO_SCHEMA"
        "4": "Table"
        "5": "CREDIT_CARD_CUSTOMERS"
        "6":
          "1":
          - - "CREDIT_CARD_NUMBER"
            - "MASK_CREDIT_CARDS"
    Create File Format CSV:
      type: "create-file-format"
      transitions:
        unconditional:
        - "SQL Script MASKING POLICIES"
      skipped: false
      parameters:
        componentName: "Create File Format CSV"
        createReplace: "Create if not exists"
        database: "DEMO_DATABASE"
        schema: "DEMO_SCHEMA"
        fileFormatName: "CSV_FILE_FORMAT"
        fileType: "CSV"
        compression: "AUTO"
        recordDelimiter: ""
        fieldDelimiter: ","
        skipHeader: "1"
        skipBlankLines: "True"
        dateFormat: ""
        timeFormat: ""
        timestampFormat: ""
        escape: ""
        escapeUnenclosedField: ""
        trimSpace2: "False"
        fieldOptionallyEnclosed: ""
        nullIf2:
        errorOnColumnCountMismatch: "True"
        emptyFieldAsNull: "True"
        replaceInvalidCharacters: "True"
        encodingType: ""
  variables:
    filename:
      metadata:
        type: "TEXT"
        description: ""
        scope: "SHARED"
        visibility: "PUBLIC"
      defaultValue: "customer_data_1"
design:
  components:
    Start 0:
      position:
        x: -544
        "y": -96
      tempMetlId: 3924
    S3 Load Data:
      position:
        x: 208
        "y": -96
      tempMetlId: 3936
    Create Table Credit Card:
      position:
        x: -395
        "y": -103
      tempMetlId: 3952
    SQL Script MASKING POLICIES:
      position:
        x: -112
        "y": -96
      tempMetlId: 4213
    Alter Masking Policy CREDIT_CARD:
      position:
        x: 48
        "y": -96
      tempMetlId: 4277
    Create File Format CSV:
      position:
        x: -256
        "y": -95
      tempMetlId: 4400
